@c This is part of the GNU Mailutils manual.
@c Copyright (C) 1999,2000,2001,2002,2003,2004,
@c 2007 Free Software Foundation, Inc.
@c See file mailutils.texi for copying conditions.
@comment *******************************************************************

@menu
* POP3::      POP3
* IMAP4::     IMAP4
* Mbox::      Mbox
* Mh::        Mh
* Maildir::   Maildir
* SMTP::      SMTP
* Sendmail::  Sendmail
* Parse822::  Parse822
@end menu

@node POP3
@comment  node-name,  next,  previous,  up
@section POP3
@cindex POP3
@include pop3.texi

@node IMAP4
@comment  node-name,  next,  previous,  up
@section IMAP4
@cindex IMAP4
@include imap4.texi

@node Mbox
@comment  node-name,  next,  previous,  up
@section Mbox
@cindex Mbox
@include mbox.texi

@node Mh
@comment  node-name,  next,  previous,  up
@section Mh
@cindex Mh
@include mh.texi

@node Maildir
@comment  node-name,  next,  previous,  up
@section Maildir
@cindex Maildir
@include maildir.texi

@node SMTP
@comment  node-name,  next,  previous,  up
@section SMTP
@cindex SMTP
@include smtp.texi

@node Sendmail
@comment  node-name,  next,  previous,  up
@section Sendmail
@cindex Sendmail
@include sendmail.texi

@node Parse822
@comment  node-name,  next,  previous,  up
@section Parse822
@cindex Parse822
@include parse822.texi
