\input texinfo  @c -*-texinfo-*-
@c %**start of header
@setfilename mailutils.info
@settitle GNU Mailutils, Programming Manual
@setchapternewpage off
@finalout
@c %**end of header

@c This file has the new style title page commands.
@c Run `makeinfo' rather than `texinfo-format-buffer'.
@c smallbook
@c tex
@c \overfullrule=0pt
@c end tex

@include version.texi

@c Combine indices.
@syncodeindex ky cp

@defcodeindex op
@syncodeindex op fn
@syncodeindex vr fn
@syncodeindex tp fn

@ifinfo
@dircategory GNU libraries
@direntry
* mailutils: (mailutils).            API for mailboxes and mail protocols.
@end direntry
@dircategory GNU utilities
@direntry
* comsatd: (mailutils)comsatd.       Comsat daemon.
* frm: (mailutils)frm.               List headers from a mailbox.
* guimb: (mailutils)guimb.           Mailbox scanning and processing language.
* imap4d: (mailutils)imap4d.         IMAP4 daemon.
* mail.local: (mailutils)mail.local. Deliver mail to the local mailbox.
* mail: (mailutils)mail.             Send and receive mail.
* messages: (mailutils)messages.     Count the number of messages in a mailbox.
* pop3d: (mailutils)pop3d.           POP3 daemon.
* readmsg: (mailutils)readmsg.       Extract messages from a folder.
* sieve: (mailutils)sieve.           Mail filtering utility.
* mailutils-config: (mailutils)mailutils-config. Get the information about the Mailutils build.
@end direntry
@end ifinfo

@copying
Published by the Free Software Foundation,
59 Temple Place - Suite 330
Boston, MA 02111-1307, USA

Copyright @copyright{} 1999, 2000, 2001, 2002, 2003 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU Manual'',
and with the Back-Cover Texts as in (a) below.  A copy of the license
is included in the section entitled ``GNU Free Documentation License''.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end copying

@titlepage
@title GNU Mailutils
@subtitle version @value{VERSION}, @value{UPDATED}
@author Alain Magloire et al.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@page
@summarycontents
@page

@node Top, Introduction, (dir), (dir)
@comment  node-name,  next,  previous,  up

@ifinfo
@chapter GNU Mailutils
This edition of the @cite{GNU Mailutils Manual}, last updated @value{UPDATED},
documents GNU Mailutils Version @value{VERSION}.
@end ifinfo

@menu
* Introduction::            GNU Mailutils.
* libmailbox::              Main library.
* libmuauth::               Auxiliary library for authenticating users.
* libmu_scm::               Interface with Guile.
* libsieve::                GNU implementation of Sieve mail filtering.
* Programs::                Programs.
* Reporting Bugs::          How to report a bug.
* News::                    Where to get information about @sc{gnu} Mailutils.
* Acknowledgement::         Thanks and Credits.

Appendices

* GNU FDL::                 This manual is under the GNU Free
                            Documentation License.
Indices
* Function Index::          All Mailutils Functions.
* Program Index::           All Mailutils Programs.
* Concept Index::           Index of Concepts.

@end menu

@node Introduction, libmailbox, Top, Top
@comment  node-name,  next,  previous,  up
@chapter Introduction
@cindex Introduction

@sc{gnu} Mailutils offers a general purpose library whose aim is to
provide a rich set of functions for accessing different mailbox formats and
mailers.

@section References

For more information on,

@itemize @bullet
@item
SMTP

@itemize @minus
@item
@cite{RFC 2821: Simple Mail Transfer Protocol}

@item
@cite{RFC 2368: The mailto URL scheme}
@end itemize

@item
POP3

@itemize @minus
@item
@cite{RFC 1939: Post Office Protocol - Version 3}

@item
@cite{RFC 1734: POP3 AUTHentication command}

@item
@cite{RFC 1957: Some Observations on Implementations of the Post Office
Protocol (POP3)}

@item
@cite{RFC 2449: POP3 Extension Mechanism}

@item
@cite{RFC 2384: POP URL Scheme}
@end itemize

@item
IMAP4

@itemize @minus
@item
@cite{RFC 2060: INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1}

@item
@cite{RFC 2088: IMAP4 non-synchronizing literals}

@item
@cite{RFC 2193: IMAP4 Mailbox Referrals}

@item
@cite{RFC 2221: IMAP4 Login Referrals}

@item
@cite{RFC 2342: IMAP4 Namespace}

@item
@cite{RFC 2192: IMAP URL Scheme}

@item
@cite{RFC 1731: IMAP4 Authentication Mechanisms}

@item
@cite{RFC 2245: Anonymous SASL Mechanism}

@end itemize

@item
message formats

@itemize @minus
@item
@cite{RFC 2822: Internet Message Format}

@item
@cite{RFC 2045: Multipurpose Internet Mail Extensions (MIME) Part One:
Format of Internet Message Bodies}

@item
@cite{RFC 2046: Multipurpose Internet Mail Extensions (MIME) Part Two:
Media Types}

@item
@cite{RFC 2047: Multipurpose Internet Mail Extensions (MIME) Part Three:
Message Header Extensions for Non-ASCII Text}

@item
@cite{RFC 2049: Multipurpose Internet Mail Extensions (MIME) Part Five:
Conformance Criteria and Examples}

@item
@cite{RFC 2111: Content-ID and Message-ID Uniform Resource Locators}
@end itemize

@item
miscellaneous related topics

@itemize @minus
@item
@cite{RFC 3028: Sieve: A Mail Filtering Language}

@item
@cite{RFC 2298: An Extensible Message Format for Message Disposition
Notifications}

@item
@cite{RFC 1738: Uniform Resource Locators (URL)}

@item
@cite{Internet Email Protocols: A Developer's Guide, by Kevin Johnson}
@end itemize

@end itemize

@node libmailbox, libmuauth, Introduction, Top
@comment  node-name,  next,  previous,  up
@chapter Framework
@cindex Framework

@include framework.texi

@node libmuauth, libmu_scm, libmailbox, Top
@chapter Authentication Library
@cindex Authentication Library
@cindex libmuauth

@include libmuauth.texi

@node libmu_scm, libsieve, libmuauth, Top
@chapter Mailutils to Scheme interface
@cindex Scheme
@cindex libmu_scm

@include libmu_scm.texi

@node libsieve, Programs, libmu_scm, Top
@chapter Sieve Library
@cindex Sieve Library
@cindex libsieve
@include libsieve.texi

@node Programs, Reporting Bugs, libsieve, Top
@comment  node-name,  next,  previous,  up
@chapter Programs
@cindex Programs

@include programs.texi

@page
@node Reporting Bugs, News, Programs, Top
@comment  node-name,  next,  previous,  up
@chapter Reporting Bugs
@cindex Reporting Bugs

Email bug reports to @email{bug-mailutils@@gnu.org}.
Be sure to include the word ``mailutils'' somewhere in the ``Subject:''
field.

As the purpose of bug reporting is to improve software, please be sure
to include maximum information when reporting a bug. The information
needed is:

@itemize
@item Version of the package you are using.
@item Compilation options used when configuring the package.
@item Conditions under which the bug appears.
@end itemize

The archives of bug-mailutils mailing list are available from
@url{http://mail.gnu.org/mailman/listinfo/bug-mailutils}.

@node News, Acknowledgement, Reporting Bugs, Top
@chapter Getting News About @sc{gnu} Mailutils

The two places to look for any news regarding @sc{gnu} Mailutils are the
Mailutils homepage at @url{http://www.gnu.org/software/mailutils}, and the
project page at @url{http://savannah.gnu.org/projects/mailutils}.

The updated versions of this manual are available online from
@url{http://www.gnu.org/software/mailutils/manual}.

@node Acknowledgement, GNU FDL, News, Top
@comment  node-name,  next,  previous,  up
@chapter Acknowledgement
@cindex Acknowledgement

In no particular order,

@itemize @bullet
@item
Jakob Kaivo @email{jkaivo@@ndn.net},
@item
Jeff Bailey @email{jbailey@@gnu.org},
@item
Sean Perry @email{shaleh@@debian.org},
@item
Thomas Fletcher @email{thomasf@@qnx.com},
@item
Dave Inglis @email{dinglis@@qnx.com},
@item
Brian Edmond @email{briane@@qnx.com},
@item
Sam Roberts @email{sroberts@@uniserve.com},
@item
Sergey Poznyakoff @email{gray@@Mirddin.farlep.net},
@item
Fran@,{c}ois Pinard  @email{pinard@@IRO.UMontreal.CA}.
@item
Jordi Mallach @email{jordi@@sindominio.net}
@item
Wojciech Polak @email{polak@@gnu.org}
@end itemize
@page


@node GNU FDL, Function Index, Acknowledgement, Top
@comment node-name,  next,  previous,  up
@include fdl.texi


@node Function Index, Program Index, GNU FDL, Top
@comment node-name,  next,  previous,  up
@unnumbered Function Index

This is an alphabetical list of all Mailutils functions.

@printindex fn
@page

@node Program Index, Concept Index, Function Index, Top
@comment node-name,  next,  previous,  up
@unnumbered Program Index

@printindex pg
@page

@node Concept Index, , Program Index, Top
@comment node-name,  next,  previous,  up
@unnumbered Concept Index

This is a general index of all issues discussed in this manual

@printindex cp
@page

@contents

@bye
