\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename mailutils.info
@settitle GNU Mailutils Manual
@setchapternewpage odd
@finalout
@c %**end of header

@c This file has the new style title page commands.
@c Run `makeinfo' rather than `texinfo-format-buffer'.
@c smallbook
@c tex
@c \overfullrule=0pt
@c end tex

@include version.texi

@c Combine indices.
@defcodeindex op
@syncodeindex op fn
@syncodeindex tp fn

@ifinfo
@dircategory Email
@direntry
* Mailutils: (mailutils).       Utilities & library for mailboxes, protocols.
@end direntry
@dircategory Individual utilities
@direntry
* comsatd: (mailutils)comsatd.                  Comsat daemon.
* frm: (mailutils)frm.                          List headers from a mailbox.
* guimb: (mailutils)guimb.                      Mailbox processing language.
* imap4d: (mailutils)imap4d.                    IMAP4 daemon.
* mail.local: (mailutils)mail.local.            Deliver mail to local mailbox.
* mail: (mailutils)mail.                        Send and receive mail.
* messages: (mailutils)messages.                Count messages in mailbox.
* pop3d: (mailutils)pop3d.                      POP3 daemon.
* readmsg: (mailutils)readmsg.                  Extract messages from a folder.
* sieve: (mailutils)sieve.                      Mail filtering utility.
@end direntry
@end ifinfo

@copying
Published by the Free Software Foundation,
51 Franklin Street, Fifth Floor
Boston, MA 02110-1301, USA

Copyright @copyright{} 1999, 2000, 2001, 2002, 2003, 2004
Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover texts being ``A GNU Manual'',
and with the Back-Cover Texts as in (a) below.  A copy of the license
is included in the section entitled ``GNU Free Documentation License''.

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end copying

@titlepage
@title GNU Mailutils
@subtitle version @value{VERSION}, @value{UPDATED}
@author Alain Magloire et al.
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@page
@summarycontents
@page
@contents

@node Top, Introduction, (dir), (dir)
@comment  node-name,  next,  previous,  up

@ifinfo
@chapter GNU Mailutils
This edition of the @cite{GNU Mailutils Manual}, last updated @value{UPDATED},
documents GNU Mailutils Version @value{VERSION}.
@end ifinfo

@menu
* Introduction::            Preliminary Information.
* Programs::                Mailutils Programs.
* Libraries::               Mailutils Libraries.
* Sieve Language::          The Sieve Language.
* Reporting Bugs::          How to Report a Bug.
* News::                    Getting News About @sc{gnu} Mailutils.
* Acknowledgement::         Thanks and Credits.

Appendices

* References::              References.
* GNU FDL::                 This manual is under the GNU Free
                            Documentation License.

Indices

* Function Index::          All Mailutils Functions.
* Variable Index::          All Mailutils Variables.
* Keyword Index::           Index of Keywords.
* Program Index::           All Mailutils Programs.
* Concept Index::           Index of Concepts.

@end menu

@node Introduction, Programs, Top, Top
@comment  node-name,  next,  previous,  up
@chapter Introduction

@sc{gnu} Mailutils contains a series of useful mail clients, servers,
and libraries.  These are the primary mail utilities of the GNU system.
Specifically, this package contains a POP3 server, an IMAP4 server,
and a Sieve mail filter.  It also provides a POSIX `mailx' client,
and a collection of other tools.  The central library is capable of
accessing different mailbox formats and mailers as well as off of
local or remote POP3 and IMAP4 servers.

This software is part of the GNU Project and belongs to the Free
Software Foundation.  All libraries are licensed using the GNU LGPL.
The documentation is licensed under the GNU FDL, and everything
else is licensed using the GNU GPL.

@subheading Why use this package?

This package started off to try and handle large mailbox files more
gracefully then current POP3 servers did.  While it handles this task,
it also allows you to support a variety of different mailbox formats
without any real effort on your part.  Also, if a new format is added
at a later date, your program will support that new format
automatically as soon as it is compiled against the new library.

@node Programs, Libraries, Introduction, Top
@comment  node-name,  next,  previous,  up
@chapter Mailutils Programs
@cindex Programs
@include programs.texi

@node Libraries, Sieve Language, Programs, Top
@comment  node-name,  next,  previous,  up
@chapter Mailutils Libraries
@cindex Libraries

@menu
* libmailbox::      The Core Library.
* libmuauth::       Auxiliary Library for Authenticating Users.
* libmu_scm::       Mailutils to Scheme Interface.
* libsieve::        GNU Implementation of Sieve Mail Filtering.
@end menu

@node libmailbox, libmuauth, Libraries, Libraries
@comment  node-name,  next,  previous,  up
@section Framework
@cindex Framework
@include framework.texi

@node libmuauth, libmu_scm, libmailbox, Libraries
@comment node-name,  next,  previous,  up
@section Authentication Library
@cindex Authentication Library
@cindex libmuauth
@include libmuauth.texi

@node libmu_scm, libsieve, libmuauth, Libraries
@comment node-name,  next,  previous,  up
@section Mailutils to Scheme Interface
@cindex Scheme
@cindex libmu_scm
@include libmu_scm.texi

@node libsieve,  , libmu_scm, Libraries
@comment node-name,  next,  previous,  up
@section Sieve Library
@cindex Sieve Library
@cindex libsieve
@include libsieve.texi

@node Sieve Language, Reporting Bugs, Libraries, Top
@comment node-name,  next,  previous,  up
@chapter Sieve Language
@cindex Sieve Language
@include sieve.texi

@node Reporting Bugs, News, Sieve Language, Top
@comment node-name,  next,  previous,  up
@chapter Reporting Bugs

Email bug reports to @email{bug-mailutils@@gnu.org}.
Be sure to include the word ``mailutils'' somewhere
in the ``Subject:'' field.

As the purpose of bug reporting is to improve software, please be sure
to include maximum information when reporting a bug. The information
needed is:

@itemize
@item Version of the package you are using.
@item Compilation options used when configuring the package.
@item Conditions under which the bug appears.
@end itemize

The archives of bug-mailutils mailing list are available from
@url{http://mail.gnu.org/@/mailman/@/listinfo/@/bug-mailutils}.

@node News, Acknowledgement, Reporting Bugs, Top
@comment node-name,  next,  previous,  up
@chapter Getting News About @sc{gnu} Mailutils

The two places to look for any news regarding @sc{gnu} Mailutils are the
Mailutils homepage at @url{http://www.gnu.org/@/software/@/mailutils}, and the
project page at @url{http://savannah.gnu.org/@/projects/@/mailutils}.

The updated versions of this manual are available online from
@url{http://www.gnu.org/@/software/@/mailutils/@/manual}.

@node Acknowledgement, References, News, Top
@comment node-name,  next,  previous,  up
@chapter Acknowledgement

In no particular order,

@itemize @bullet
@item
Jakob Kaivo @email{jkaivo@@ndn.net},
@item
Jeff Bailey @email{jbailey@@gnu.org},
@item
Sean Perry @email{shaleh@@debian.org},
@item
Thomas Fletcher @email{thomasf@@qnx.com},
@item
Dave Inglis @email{dinglis@@qnx.com},
@item
Brian Edmond @email{briane@@qnx.com},
@item
Sam Roberts @email{sroberts@@uniserve.com},
@item
Sergey Poznyakoff @email{gray@@Mirddin.farlep.net},
@item
Fran@,{c}ois Pinard  @email{pinard@@IRO.UMontreal.CA}.
@item
Jordi Mallach @email{jordi@@sindominio.net}
@item
Wojciech Polak @email{polak@@gnu.org}
@end itemize

@node References, GNU FDL, Acknowledgement, Top
@comment node-name,  next,  previous,  up
@appendix References

@itemize @bullet
@item SMTP

@itemize @minus
@item
@cite{RFC 2821: Simple Mail Transfer Protocol}

@item
@cite{RFC 2368: The mailto URL scheme}

@item
@cite{RFC 2487: SMTP Service Extension for Secure SMTP over TLS}
@end itemize

@item POP3

@itemize @minus
@item
@cite{RFC 1939: Post Office Protocol - Version 3}

@item
@cite{RFC 1734: POP3 AUTHentication command}

@item
@cite{RFC 1957: Some Observations on Implementations of the Post Office
Protocol (POP3)}

@item
@cite{RFC 2449: POP3 Extension Mechanism}

@item
@cite{RFC 2384: POP URL Scheme}

@item
@cite{RFC 2595: Using TLS with IMAP, POP3 and ACAP}
@end itemize

@item IMAP4

@itemize @minus
@item
@cite{RFC 2060: INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1}

@item
@cite{RFC 2088: IMAP4 non-synchronizing literals}

@item
@cite{RFC 2193: IMAP4 Mailbox Referrals}

@item
@cite{RFC 2221: IMAP4 Login Referrals}

@item
@cite{RFC 2342: IMAP4 Namespace}

@item
@cite{RFC 2192: IMAP URL Scheme}

@item
@cite{RFC 1731: IMAP4 Authentication Mechanisms}

@item
@cite{RFC 2245: Anonymous SASL Mechanism}

@item
@cite{RFC 2595: Using TLS with IMAP, POP3 and ACAP}
@end itemize

@item message formats

@itemize @minus
@item
@cite{RFC 2822: Internet Message Format}

@item
@cite{RFC 2045: Multipurpose Internet Mail Extensions (MIME) Part One:
Format of Internet Message Bodies}

@item
@cite{RFC 2046: Multipurpose Internet Mail Extensions (MIME) Part Two:
Media Types}

@item
@cite{RFC 2047: Multipurpose Internet Mail Extensions (MIME) Part Three:
Message Header Extensions for Non-ASCII Text}

@item
@cite{RFC 2049: Multipurpose Internet Mail Extensions (MIME) Part Five:
Conformance Criteria and Examples}

@item
@cite{RFC 2111: Content-ID and Message-ID Uniform Resource Locators}
@end itemize

@item miscellaneous related topics

@itemize @minus
@item
@cite{RFC 1738: Uniform Resource Locators (URL)}

@item
@cite{RFC 2298: An Extensible Message Format for Message Disposition
Notifications}

@item
@cite{RFC 3028: Sieve: A Mail Filtering Language}

@item
@cite{RFC 3431: Sieve Extension: Relational Tests}

@item
@cite{Internet Email Protocols: A Developer's Guide, by Kevin Johnson}
@end itemize
@end itemize

@node GNU FDL, Function Index, References, Top
@comment node-name,  next,  previous,  up
@include fdl.texi

@node Function Index, Variable Index, GNU FDL, Top
@comment node-name,  next,  previous,  up
@unnumbered Function Index

This is an alphabetical list of all Mailutils functions.

@printindex fn
@page

@node Variable Index, Keyword Index, Function Index, Top
@unnumbered Variable Index
@printindex vr
@page

@node Keyword Index, Program Index, Variable Index, Top
@unnumbered Keyword Index
@printindex ky
@page

@node Program Index, Concept Index, Keyword Index, Top
@comment node-name,  next,  previous,  up
@unnumbered Program Index

@printindex pg
@page

@node Concept Index,  , Program Index, Top
@comment node-name,  next,  previous,  up
@unnumbered Concept Index

This is a general index of all issues discussed in this manual

@printindex cp

@bye
