#! /bin/sh
# GNU Mailutils -- a suite of utilities for electronic mail
# Copyright (C) 2002, 2007, 2010 Free Software Foundation, Inc.
#
# GNU Mailutils is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# GNU Mailutils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GNU Mailutils.  If not, see <http://www.gnu.org/licenses/>. 


if [ "$1" = "-r" ]; then
	shift
	rm -rf $*
	exit 0
fi

mkdirhier() {
	dir=""
	for d in `echo $1|sed 's,/, ,g'`
	do
		dir="$dir/$d"
		test -d $dir || mkdir $dir
	done
}

while [ $# -gt 0 ]
do
	SRCDIR=${1:?}
	DSTDIR=${2:?}
	shift 2

	if [ ! -d $SRCDIR ]; then
		echo "$SRCDIR not a directory" >&2
		exit 1
	fi
	if [ ! -r $SRCDIR/DISTFILES ]; then
		echo "$SRCDIR/DISTFILES does not exist" >&2
		exit 1
	fi
	mkdirhier $DSTDIR
	chmod -R u+w $DSTDIR
	rm -rf $DSTDIR/*
	
	cat $SRCDIR/DISTFILES |
	while read NAME
	do
		cp $SRCDIR/$NAME $DSTDIR/$NAME
		chmod u+w $DSTDIR/$NAME
	done
done
