\input texinfo  @c -*-texinfo-*-
@c %**start of header
@setfilename mailutils.info
@settitle mailutils, Programming Manual
@c %**end of header

@c This file has the new style title page commands.
@c Run `makeinfo' rather than `texinfo-format-buffer'.

@c smallbook

@c tex
@c \overfullrule=0pt
@c end tex

@include version.texi

@c Combine indices.
@syncodeindex ky cp
@syncodeindex pg cp
@syncodeindex tp cp

@defcodeindex op
@syncodeindex op fn
@syncodeindex vr fn

@ifinfo
@direntry
* mailutils: (libmailutils).         The GNU mailutils library API.
@end direntry
This file documents @sc{mailutils},  library API.


Published by the Free Software Foundation,
59 Temple Place - Suite 330
Boston, MA 02111-1307, USA

Copyright 1999, 2000 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

@ignore
Permission is granted to process this file through TeX and print the
results, provided the printed document carries copying permission
notice identical to this one except for the removal of this paragraph
(this paragraph not being relevant to the printed manual).

@end ignore
Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Foundation.
@end ifinfo

@setchapternewpage off

@titlepage
@title mailutils, SDK.
@subtitle version @value{VERSION}, @value{UPDATED}
@author Alain Magloire et al.

@page
@vskip 0pt plus 1filll
Copyright @copyright{} 1999, 2000, 2001 Free Software Foundation, Inc.

@sp 2
Published by the Free Software Foundation, @*
59 Temple Place - Suite 330, @*
Boston, MA 02111-1307, USA

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the entire
resulting derived work is distributed under the terms of a permission
notice identical to this one.

Permission is granted to copy and distribute translations of this manual
into another language, under the above conditions for modified versions,
except that this permission notice may be stated in a translation approved
by the Foundation.

@end titlepage
@page

@summarycontents
@page

@node Top, Introduction, (dir), (dir)
@comment  node-name,  next,  previous,  up

@ifinfo
This document was produced for version @value{VERSION} of @sc{gnu}
@sc{mailutils}.
@end ifinfo
@menu
* Introduction::                GNU @sc{mailutils}
* C API::                       C API.
* Framework::                   Framework.
* Programs::                    Programs.
* Reporting Bugs::              Reporting Bugs.
* Acknowledgement::             Thanks and Credits.
* Concept Index::                All @sc{Mailutils} Functions.
* Index::

@end menu

@node Introduction, C API, Top, Top
@comment  node-name,  next,  previous,  up
@chapter Introduction
@cindex Introduction

@sc{gnu} @sc{Mailutils} offers a general purpose library whose aim is to
provide a rich set of functions for accessing different mailbox formats and
mailers.

@section References

For more information on,

@itemize @bullet
@item
SMTP RFCs:

@itemize @minus
@item
@cite{RFC 2821: Simple Mail Transfer Protocol}

@item
@cite{RFC 2822: Internet Message Format}

@item
@cite{RFC 2368: The mailto URL scheme}
@end itemize

@item
on POP3

@itemize @minus
@item
@cite{RFC 1734: POP3 AUTHentication command}

@item
@cite{RFC 1957: Some Observations on Implementations of the Post Office
Protocol (POP3)}

@item
@cite{RFC 1939: Post Office Protocol - Version 3}

@item
@cite{RFC 2449: POP3 Extension Mechanism}

@item
@cite{RFC 2384: POP URL Scheme}
@end itemize

@item
On IMAP4

@itemize @minus
@item
@cite{RFC 2088: IMAP4 non-synchronizing literals}

@item
@cite{RFC 2193: IMAP4 Mailbox Referrals}

@item
@cite{RFC 2221: IMAP4 Login Referrals}

@item
@cite{RFC 2342: IMAP4 Namespace}

@item
@cite{RFC 1738: Uniform Resource Locators (URL)}

@item
@cite{RFC 2192: IMAP URL Scheme}
@end itemize

@item
On MIME

@itemize @minus
@item
@cite{RFC 2060: INTERNET MESSAGE ACCESS PROTOCOL - VERSION 4rev1}

@item
@cite{RFC 2045: Multipurpose Internet Mail Extensions (MIME) Part One:
Format of Internet Message Bodies}

@item
@cite{RFC 2047: MIME (Multipurpose Internet Mail Extensions) Part Three:
Message Header Extensions for Non-ASCII Text}

@item
@cite{RFC 2049: Multipurpose Internet Mail Extensions (MIME) Part Five:
Conformance Criteria and Examples}

@item
@cite{RFC 2111: Content-ID and Message-ID Uniform Resource Locators}
@end itemize

@item
Misc
@cite{RFC 3028: Sieve: A Mail Filtering Language}

@item
@cite{Internet Email Protocols a Developer's Guide by Kevin Johnson}
@end itemize

@node C API, Framework, Introduction, Top
@comment  node-name,  next,  previous,  up
@chapter C API
@cindex C API

@include c-api.texi

@node Framework, Programs, C API, Top
@comment  node-name,  next,  previous,  up
@chapter Framework
@cindex Framework

@include framework.texi

@node Programs, Reporting Bugs, Framework, Top
@comment  node-name,  next,  previous,  up
@chapter Programs
@cindex Programs

@include programs.texi

@node Reporting Bugs, Acknowledgement, Programs, Top
@comment  node-name,  next,  previous,  up
@chapter Reporting Bugs
@cindex Reporting Bugs

Email bug reports to @email{bug-mailutils@@gnu.org}.
Be sure to include the word ``mailutils'' somewhere in the ``Subject:'' field.

@node Acknowledgement, Concept Index , Reporting Bugs, Top
@comment  node-name,  next,  previous,  up
@chapter Acknowledgement
@cindex Acknowledgement

In no particular order,
Jakob Kaivo @email{jkaivo@@ndn.net},
Jeff Bailey @email{jbailey@@gnu.org},
Sean Perry @email{shaleh@@debian.org},
Thomas Fletcher @email{thomasf@@qnx.com},
Dave Inglis @email{dinglis@@qnx.com},
Brian Edmond @email{briane@@qnx.com},
Sam Roberts @email{sroberts@@uniserve.com},
Sergey Poznyakoff @email{gray@@Mirddin.farlep.net},
Fran@,{c}ois Pinard  @email{pinard@@IRO.UMontreal.CA}.
@page

@node Concept Index, Index, Acknowledgement, Top
@comment node-name,  next,  previous,  up
@unnumbered Concept Index

This is a general index of all issues discussed in this manual

@printindex cp
@page

@node Index,  , Concept Index, Top
@comment node-name,  next,  previous,  up
@unnumbered Index

This is an alphabetical list of all @sc{mailutils} functions.

@printindex fn

@contents

@bye
