#! /bin/sh
# Extract the initialization actions for builtin things.
#
#  Copyright (C) 1999, 2000, 2007 Free Software Foundation, Inc.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this software; see the file COPYING.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301 USA
#
## For some obscure reason, the original guile-doc-snarf distributed
## with guile up to version 1.4, passes guile-func-name-check
## to awk without absolute path spec. Consequently the script bails
## out unless guile-func-name-check is in the current directory.
## This version assumes that both scripts live in the same directory
## and deduces the path to guile-func-name-check from the own pathname.
## --gray

OUTFILE=/dev/tty
DOCFILE=0

# process aruments
while [ $# -gt 0 ];
do
    case $1 in
    -o) OUTFILE=$2; shift 2;;
    -d) DOCFILE=1; shift;;
    *)  break;;
    esac
done    

fullfilename=$1; shift

# strip path to source directory
filename=`basename $fullfilename`

if [ $DOCFILE -ne 0 ]; then
    dot_doc=$OUTFILE
    OUTFILE=/dev/null
else
    # we need to be sure that the .x file exists
    # since the .c/.cc file may include it
    # (the old guile-snarf did not have this problem
    #  because the makefile redirects output to the .x file
    #  which creates the file before the inclusion occurs)
    # --12/12/99 gjb
    no_ext=`echo $filename | sed 's/\.[^.]*$//g'`
    dot_doc=${no_ext}.doc
fi

temp="/tmp/snarf.$$"
trap "rm -f $temp" 0 1 2 15

## Let the user override the preprocessor & awk autoconf found.
test -n "${CPP+set}" || CPP="gcc -E"
test -n "${AWK+set}" || AWK="gawk"

## Must run guile-func-name-check on the unpreprocessed source
${AWK} -f `dirname $0`/guile-func-name-check "$fullfilename"

## We must use a temporary file here, instead of a pipe, because we
## need to know if CPP exits with a non-zero status.
echo "/* empty */" > $OUTFILE
${CPP} -DSCM_MAGIC_SNARFER $fullfilename "$@" > ${temp}
if [ $? -ne 0 ]; then
    rm -f $OUTFILE
    exit 1
fi

cat ${temp} | \
sed 's/^\(.\{128\}.\{128\}.\{128\}.\{128\}.\{128\}.\{128\}.\{128\}.\{128\}\).*/\1/g' | \
${AWK} -f `dirname $0`/guile-snarf.awk `basename ${dot_doc}` > $OUTFILE
