#!/bin/sh

#   set -x

    cp INBOX.orig INBOX

    echo == Parse testing
    for t in ex-*.sv
    do
    	echo Test: $t
    	../sieve -c $t
    done

    for t in exn-*.sv
    do
    	echo Test: $t might fail
	#../sieve -ncv -f ./INBOX $t || true
    done

    echo == Action testing
    for t in ex-*.sv
    do
    	cp INBOX.orig INBOX
    	echo
    	echo Test: $t
    	../sieve -f ./INBOX $t
    done

