From: "Lemuel Gulliver, esq." <gulliver@example.net>
To: root
Subject: Travels into several remote Nations of the World

A LETTER from Capt. Gulliver, to his Cousin Sympson 

I HOPE you will be ready to own publickly, whenever you shall be called 
to it, that by your great and frequent Urgency you prevailed on me to 
publish a very loose and uncorrect Account of my Travels; with Direction 
to hire some young Gentlemen of either University to put them in Order, 
and correct the Style, as my Cousin Dampier did by my Advice, in his 
Book called A Voyage round the World. But I do not remember I gave you 
Power to consent that any thing should be omitted, and much less that any 
thing should be inserted: therefore, as to the latter, I do here renounce 
every thing of that Kind; particularly a Paragraph about her Majesty the 
late Queen Anne, of most pious and glorious Memory; although I did 
reverence and esteem her more than any of human Species. But you, or 
your Interpolator, ought to have considered, that as it was not my 
Inclination, so was it not decent to praise any Animal of our Composition 
before my Master Houyhnhnm: And besides the Fact was altogether false; 
for to my Knowledge, being in England during some Part of her Majesty's 
Reign, she did govern by a chief Minister; nay, even by two successively; 
the first whereof was the Lord of Godolphin, and the second the Lord of 
Oxford; so that you have made me say the thing that was not. Likewise, in 
the Account of the Academy of Projectors, and several Passages of my 
Discourse to my Master Houyhnhnm, you have either omitted some 
material Circumstances, or minced or changed them in such a Manner, that 
I do hardly know mine own Work. When I formerly hinted to you 
something of this in a Letter, you were pleased to answer that you were 
afraid of giving Offense; that People in Power were very watchful over the 
Press, and apt not only to interpret, but to punish every thing which looked 
like an Innuendo (as I think you called it.) But pray, how could that which 
I spoke so many Years ago, and at about five Thousand leagues distance, in 
another Reign, be applied to any of the Yahoos who now are said to govern 
the Herd; especially at a time when I little thought on or feared the 
Unhappiness of living under them. Have not I the most reason to complain, 
when I see these very Yahoos carried by Houyhnhnms in a Vehicle, as if 
these were Brutes, and those the rational Creatures? And indeed, to avoid 
so monstrous and detestable a Sight was one principal Motive of my 
Retirement hither. 

Thus much I thought proper to tell you in Relation to yourself, and to the 
Trust I reposed in you. 

